# Generated by Django 6.0.4 on 2026-04-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='接口名称')),
                ('url', models.URLField(help_text='例如: https://itunes.apple.com/search', max_length=500, verbose_name='接口地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=0, help_text='数字越小优先级越高', verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '刮削接口配置',
                'verbose_name_plural': '刮削接口配置',
                'ordering': ['priority', '-id'],
            },
        ),
    ]
