# Generated by Django 6.0.4 on 2026-04-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '正在扫描'), ('completed', '扫描完成'), ('error', '扫描出错')], default='pending', max_length=20)),
                ('target_path', models.CharField(max_length=1024, verbose_name='目标路径')),
                ('total_files', models.IntegerField(default=0, verbose_name='总文件数')),
                ('processed_files', models.IntegerField(default=0, verbose_name='已处理数')),
                ('added_count', models.IntegerField(default=0, verbose_name='新增数量')),
                ('updated_count', models.IntegerField(default=0, verbose_name='更新数量')),
                ('current_file', models.CharField(blank=True, max_length=1024, null=True, verbose_name='当前正在处理的文件')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
