# Generated by Django 6.0.4 on 2026-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='deleted_count',
            field=models.IntegerField(default=0, verbose_name='删除数量'),
        ),
    ]
