# Generated by Django 6.0.4 on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scantask_deleted_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('music_path', '音乐文件路径')], max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.CharField(max_length=1024, verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='配置描述')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
    ]
