/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppleConfirmModal: typeof import('./components/AppleConfirmModal.vue')['default']
    AppleProgressModal: typeof import('./components/AppleProgressModal.vue')['default']
    AppleToast: typeof import('./components/AppleToast.vue')['default']
    EditTrackModal: typeof import('./components/EditTrackModal.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    PlayerDetail: typeof import('./components/PlayerDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScraperContent: typeof import('./components/ScraperContent.vue')['default']
    ToastMessage: typeof import('./components/ToastMessage.vue')['default']
    TrackList: typeof import('./components/TrackList.vue')['default']
    TrashContent: typeof import('./components/TrashContent.vue')['default']
    VolumeTooltip: typeof import('./components/VolumeTooltip.vue')['default']
  }
}
